# Generated by Django 3.0.3 on 2020-09-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('omschrijving', models.CharField(max_length=1000)),
                ('datum', models.DateField()),
            ],
        ),
    ]
